export const INPUT_TASK_TEXT = "INPUT_TASK_TEXT";
export const CREATE_TASK = "CREATE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const ADD_DRAFT_TASK_TEXT = "ADD_DRAFT_TASK_TEXT";
export const EDIT_DRAFT_TASK_TEXT = "EDIT_DRAFT_TASK_TEXT";